### ISSUE TITLE
Shallow policy network

### ISSUE THREAD

**Issue by ttrine** [Rochester-NRT/RocAlphaGo#8]
Data
- What shape are the input tensors?
- What features do the input tensors encode?

Architecture
- How many hidden layers?
- How big should each hidden layer be?

**Comment by wrongu** [comment]
The architecture is hidden in the main text. It looks like  they simply have a linear weighting of the features evaluated at each position:

> We also trained a faster but less accurate rollout policy pπ(a|s), using a linear softmax of small pattern features
> (Silver et al. page 2)

The real difficulty here is in implementing the features.

**Comment by wrongu** [comment]
This linear regression with softmax could be implemented as a single convolutional layer with 1x1 kernel size

To-be-benchmarked… but I worry that one-hot encodings of vectors of the order of 10000 dimensions will be a big efficiency bottleneck. Since these features will be dot-product’d with a vector of weights, the one-hot element is essentially acting a look-up into that weight vector. In other words,  `dot([a b c d e],  [0 0 0 1 0])` is just `d`
    
So (if it turns out to be a big speedup) we should consider trying to implement this as a ‘lookup’ of the nth weight rather than as convolutional features

**Comment by wrongu** [comment]
Redundant with #48
